name: Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  run-node-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        deno-version: [1.42.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run docker compose
        run: docker compose up -d

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm test

      - name: Run deno tests
        run: npm run test:deno

  run-misc-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Type Check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint
